FROM cr.yandex/mirror/ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive
RUN useradd -ms /bin/bash --uid 1000 jupyter\
&& apt update\
&& apt-get install -y git\
&& apt install -y python3.10-dev python3.10-distutils curl\
&& ln -s /usr/bin/python3.10 /usr/local/bin/python3\
&& curl https://bootstrap.pypa.io/get-pip.py | python3 \
&& pip install --no-cache-dir torch numpy pandas matplotlib transformers datasets\
&& echo "DEBUG"